// frontend/src/app/login/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useForm } from 'react-hook-form'
import { authService } from '@/lib/auth'
import { useAuth } from '@/hooks/useAuth'

interface LoginForm {
  email: string
  first_name?: string
  last_name?: string
}

interface VerifyForm {
  otp_code: string
}

export default function LoginPage() {
  const router = useRouter()
  const { setUser } = useAuth()
  const [step, setStep] = useState<'email' | 'otp'>('email')
  const [email, setEmail] = useState('')
  const [isNewUser, setIsNewUser] = useState(false)
  const [showRegistrationFields, setShowRegistrationFields] = useState(false)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  const { register: registerEmail, handleSubmit: handleSubmitEmail, formState: { errors: emailErrors } } = useForm<LoginForm>()
  const { register: registerOTP, handleSubmit: handleSubmitOTP, formState: { errors: otpErrors } } = useForm<VerifyForm>()

  const onSubmitEmail = async (data: LoginForm) => {
    setLoading(true)
    setError('')
    
    try {
      const response = await authService.requestOTP(data)
      setEmail(data.email)
      setIsNewUser(response.is_new_user)
      setStep('otp')
    } catch (err: any) {
      const errorMessage = err.response?.data?.detail || 'Failed to send OTP'
      setError(errorMessage)
      
      // If the error is about missing first/last name, show the registration fields
      if (errorMessage.includes('First name and last name required')) {
        setShowRegistrationFields(true)
      }
    } finally {
      setLoading(false)
    }
  }

  const onSubmitOTP = async (data: VerifyForm) => {
    setLoading(true)
    setError('')
    
    try {
      const response = await authService.verifyOTP({
        email,
        otp_code: data.otp_code
      })
      setUser(response.user)
      router.push('/dashboard')
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Invalid OTP')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">
      <div className="max-w-md w-full space-y-8">
        <div className="text-center">
          <h1 className="text-3xl font-bold text-gray-900">UmaDex</h1>
          <p className="mt-2 text-sm text-gray-600">
            Educational Assignment Management
          </p>
        </div>

        <div className="bg-white py-8 px-4 shadow-xl rounded-lg sm:px-10">
          {step === 'email' ? (
            <form onSubmit={handleSubmitEmail(onSubmitEmail)} className="space-y-6">
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-700">
                  Email address
                </label>
                <div className="mt-1">
                  <input
                    {...registerEmail('email', {
                      required: 'Email is required',
                      pattern: {
                        value: /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i,
                        message: 'Invalid email address'
                      }
                    })}
                    type="email"
                    autoComplete="email"
                    className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500"
                    placeholder="you@example.com"
                  />
                  {emailErrors.email && (
                    <p className="mt-1 text-sm text-red-600">{emailErrors.email.message}</p>
                  )}
                </div>
              </div>

              {showRegistrationFields && (
                <>
                  <div className="text-sm text-gray-600 mb-4">
                    <p>Looks like you're new! Please provide your name to complete registration.</p>
                  </div>
                  <div>
                    <label htmlFor="first_name" className="block text-sm font-medium text-gray-700">
                      First name
                    </label>
                    <div className="mt-1">
                      <input
                        {...registerEmail('first_name', {
                          required: showRegistrationFields ? 'First name is required' : false
                        })}
                        type="text"
                        autoComplete="given-name"
                        className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500"
                      />
                      {emailErrors.first_name && (
                        <p className="mt-1 text-sm text-red-600">{emailErrors.first_name.message}</p>
                      )}
                    </div>
                  </div>

                  <div>
                    <label htmlFor="last_name" className="block text-sm font-medium text-gray-700">
                      Last name
                    </label>
                    <div className="mt-1">
                      <input
                        {...registerEmail('last_name', {
                          required: showRegistrationFields ? 'Last name is required' : false
                        })}
                        type="text"
                        autoComplete="family-name"
                        className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500"
                      />
                      {emailErrors.last_name && (
                        <p className="mt-1 text-sm text-red-600">{emailErrors.last_name.message}</p>
                      )}
                    </div>
                  </div>
                </>
              )}

              {error && (
                <div className="rounded-md bg-red-50 p-4">
                  <p className="text-sm text-red-800">{error}</p>
                </div>
              )}

              <button
                type="submit"
                disabled={loading}
                className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50"
              >
                {loading ? 'Sending...' : showRegistrationFields ? 'Register & Send Code' : 'Send Login Code'}
              </button>
            </form>
          ) : (
            <form onSubmit={handleSubmitOTP(onSubmitOTP)} className="space-y-6">
              <div className="text-center">
                <p className="text-sm text-gray-600">
                  We sent a 6-digit code to {email}
                </p>
              </div>

              <div>
                <label htmlFor="otp_code" className="block text-sm font-medium text-gray-700">
                  Login Code
                </label>
                <div className="mt-1">
                  <input
                    {...registerOTP('otp_code', {
                      required: 'Login code is required',
                      pattern: {
                        value: /^[0-9]{6}$/,
                        message: 'Code must be 6 digits'
                      }
                    })}
                    type="text"
                    maxLength={6}
                    autoComplete="one-time-code"
                    className="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-primary-500 focus:border-primary-500 text-center text-lg tracking-widest"
                    placeholder="000000"
                  />
                  {otpErrors.otp_code && (
                    <p className="mt-1 text-sm text-red-600">{otpErrors.otp_code.message}</p>
                  )}
                </div>
              </div>

              {error && (
                <div className="rounded-md bg-red-50 p-4">
                  <p className="text-sm text-red-800">{error}</p>
                </div>
              )}

              <button
                type="submit"
                disabled={loading}
                className="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-primary-500 disabled:opacity-50"
              >
                {loading ? 'Verifying...' : 'Verify Code'}
              </button>

              <button
                type="button"
                onClick={() => {
                  setStep('email')
                  setError('')
                }}
                className="w-full text-sm text-primary-600 hover:text-primary-500"
              >
                Use a different email
              </button>
            </form>
          )}
        </div>
      </div>
    </div>
  )
}

// frontend/src/views/Login.vue
<template>
  <div class="min-h-screen flex items-center justify-center bg-gray-100 py-12 px-4">
    <div class="max-w-md w-full space-y-8 p-6 bg-white rounded-lg shadow-md">
      <div>
        <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
          {{ otpSent ? 'Enter verification code' : 'Sign in to your account' }}
        </h2>
      </div>
      
      <!-- Error message -->
      <div v-if="errorMessage" class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative">
        {{ errorMessage }}
      </div>
      
      <!-- OTP Request Form -->
      <div v-if="!otpSent">
        <form class="mt-8 space-y-6" @submit.prevent="sendOTP">
          <div>
            <label for="email" class="block text-sm font-medium text-gray-700">Email address</label>
            <input 
              v-model="email" 
              id="email" 
              name="email" 
              type="email" 
              autocomplete="email" 
              required 
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Enter your email"
            >
          </div>
          
          <div>
            <button 
              type="submit" 
              :disabled="authStore.loading"
              class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
            >
              {{ authStore.loading ? 'Sending...' : 'Send verification code' }}
            </button>
          </div>
        </form>
      </div>
      
      <!-- OTP Verification Form -->
      <div v-else>
        <form class="mt-8 space-y-6" @submit.prevent="verifyOTP">
          <div>
            <label for="otp" class="block text-sm font-medium text-gray-700">Verification code</label>
            <input 
              v-model="token" 
              id="otp" 
              name="otp" 
              type="text" 
              required 
              class="mt-1 block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm"
              placeholder="Enter the code sent to your email"
            >
          </div>
          
          <div>
            <button 
              type="submit" 
              :disabled="authStore.loading"
              class="w-full flex justify-center py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:opacity-50"
            >
              {{ authStore.loading ? 'Verifying...' : 'Verify code' }}
            </button>
          </div>
          
          <div class="text-sm text-center">
            <button 
              @click="otpSent = false" 
              class="font-medium text-indigo-600 hover:text-indigo-500"
            >
              Try a different email
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'

const router = useRouter()
const authStore = useAuthStore()

const email = ref('')
const token = ref('')
const otpSent = ref(false)
const errorMessage = ref('')

const sendOTP = async () => {
  errorMessage.value = ''
  const { success, error } = await authStore.signInWithOTP(email.value)
  
  if (success) {
    otpSent.value = true
  } else if (error) {
    errorMessage.value = error.message || 'Failed to send verification code'
  }
}

const verifyOTP = async () => {
  errorMessage.value = ''
  const { success, error } = await authStore.verifyOTP(email.value, token.value)
  
  if (success) {
    router.push('/')
  } else if (error) {
    errorMessage.value = error.message || 'Failed to verify code'
  }
}
</script>
